Update from heroku main rebase
forma-ai/heroku-buildpack-python pull request #11
Opened 2021-06-09 18:13 UTC by ghedsouza

New attempt. Using the branch provided by @zhouwein which squashes our changes into a single commit. Then I made an extra commit to drop our custom pip handling.

#### Previous PRs:
- https://github.com/forma-ai/heroku-buildpack-python/pull/9
- https://github.com/forma-ai/heroku-buildpack-python/pull/10

2021-06-09 19:57 UTC, zhouwein requested changes

2021-06-09 19:57 UTC, zhouwein commented on bin/steps/pip-install
> +    cp $CLIENT_DIRNAME/requirements.txt .heroku/python/requirements-declared.txt
based on my reading of the code this should be the concatenation of the requirements.txt from backend-core and backend-client. reason being, this ends up getting diffed, so it doesn't really make sense to compare against a requirements file that has 1 line (backend-core) most of the time.

2021-06-09 19:57 UTC, zhouwein commented on vendor/pip-pop/pip-diff
> +#!/usr/bin/env python
this might be a bad merge, along with the other file (pip-grep). When comparing against master this is a file being added, but it doesn't have any other references.

2021-06-17 13:24 UTC, ghedsouza commented on bin/compile
> +export PY37 PY36 PY35 PY27 PY34
Yes, in fact these were removed here: https://github.com/heroku/heroku-buildpack-python/pull/1011/files#diff-a64a7d9b82578ca3053416d56631a61e0ceabed87619415663030e3842429e05L87

2021-06-17 13:31 UTC, ghedsouza commented on vendor/pip-pop/pip-diff
> +#!/usr/bin/env python
Yup, removed.

2021-06-17 13:37 UTC, ghedsouza commented on bin/compile
> +#mtime "sqlite3.install.time" "${start}"
Successfully removed!

2021-06-17 13:47 UTC, ghedsouza commented on bin/steps/pip-install
> +    cp $CLIENT_DIRNAME/requirements.txt .heroku/python/requirements-declared.txt
I think you're right, but I don't know if there's a way to get the requirements from backend-core at this stage. Since we're only building backend-client, and won't download backend-core until we're in the middle of the actual build process.

2021-06-17 13:48 UTC, ghedsouza commented
Testing latest branch on internal-staging-3: https://dashboard.heroku.com/apps/internal-staging-3/activity/builds/d9bec2d8-b3a8-424c-92a4-83755902820c

2021-06-21 19:23 UTC, zhouwein requested changes

2021-06-21 19:23 UTC, zhouwein commented on bin/steps/pip-uninstall
> +#!/usr/bin/env bash
this file also doesn't seem to be used.

2021-11-22 20:23 UTC, merged